<form action="" id="checkout-agreements" onsubmit="return false;">
    <?php if(Mage::helper('clientcommentorder')->_isModuleEnable() && Mage::helper('clientcommentorder')->_showInTotalField()):?>
    <ol class="checkout-agreements">
        <li>
            <p><?= Mage::helper('clientcommentorder')->getTitle(); ?></p>
            <textarea id="ordercomment-comment" class="input-text validation-passed" name="ordercomment[comment]" title="<?php echo $this->__('Order Comment') ?>" rows="5" cols="35"></textarea>
        </li>
    </ol>
    <?php endif;?>

    <?php if ($this->getAgreements()): ?>
        <ol class="checkout-agreements">
            <?php foreach ($this->getAgreements() as $_a): ?>
                <li>
                    <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
                        <?php if ($_a->getIsHtml()):?>
                            <?php echo $_a->getContent() ?>
                        <?php else:?>
                            <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                        <?php endif; ?>
                    </div>
                    <p class="agree">
                        <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) ?></label>
                    </p>
                </li>
            <?php endforeach ?>
        </ol>
    <?php endif; ?>
</form>